### ISSUE TITLE
Checklist for October 11th, 2018 - Adam's Birthday! Wooo!

### ISSUE THREAD

**Issue by Adron** [Adron/VidStreamHacking#1]
# Startup Checklist

This is a basic checklist of the things I go through before acutally starting any new stream.

 - [ ] Verify that OBS has the appropriate key setup for the stream.
 - [ ] Are all monitors set to the appropriate resolution.
 - [ ] Are all webcams running and actually set in position and available for transitioning?
 - [ ] Does OBS have the appropriate *sources* setup for the appropriate *scenes* for each respective transition.
 - [ ] Mic check all the mics:
    - [ ] Rode Podcaster http://en.rode.com/microphones/podcaster
    - [ ] Rode Shotgun NTG1 http://en.rode.com/microphones/ntg-1
    - [ ] WebCam Mic(s)
 - [ ] Are all files, media files, and related collateral ready for transitions?
 - [ ] Any other sccripts, checklists, or other items available within easy reach?

**Comment by Adron** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [VidStreamHacking Repo](https://trello.com/c/NLlnqpNk/37-vidstreamhacking-repo)
